Show filtered object count during populate
FriendsOfSymfony/FOSElasticaBundle pull request #1892
Opened 2022-11-16 12:25 UTC by bobvandevijver

With the current populate command output you are not given insight in the amount of filtered objects, and they are not used to advance the progress bar as well. Before #1891 this would result in the progress bar not being completed at all, but now it jumps to the end as it is being marked as completed.

I propose the following adjustment: register the amount of filtered objects into the `PreInserObjectsEvent` and forward to the `PostInsertObjectsEvent`. There is also a `PostAsyncInsertObjectsEvent`, but I believe that is not being used at (will open a dedicated MR for it). With the data now available to the console logger, we can print the skipped/total object after the populating message, and adjust the progress bar total to show the amount of objects to be really inserted.

I expect test will fail with this change, but before I update them I would love to hear if this is a reasonable change!

### Old output

https://user-images.githubusercontent.com/1835343/202022563-561b2bfe-749f-487a-8b33-cf9af9d5863e.mp4

### New output

https://user-images.githubusercontent.com/1835343/202179821-67ee1dd7-b5b0-4a37-9f28-9cf4cb164470.mp4

2022-12-20 10:12 UTC, bobvandevijver commented
@XWB Anything I can do for this to get merged?

2022-12-21 17:37 UTC, XWB requested changes

2022-12-21 17:37 UTC, XWB commented on src/Persister/Event/PreInsertObjectsEvent.php
> +    public function setFilteredObjectCount($count)
As we rely on PHP 7.4 it is safe to use type hints and return types.

2022-12-21 17:37 UTC, XWB commented on src/Persister/Event/PreInsertObjectsEvent.php
> +    public function getFilteredObjectCount()
You may add a return type.

2022-12-21 17:37 UTC, XWB commented on src/Persister/Event/PostInsertObjectsEvent.php
> +    private $filteredObjectCount;
```suggestion
    private int $filteredObjectCount;
```

2022-12-21 21:49 UTC, XWB approved these changes

2022-12-21 21:49 UTC, merged

2022-12-21 21:49 UTC, XWB commented
👍

2023-05-18 07:02 UTC, bobvandevijver commented
@XWB I would love to see a release coming soon :)